### ISSUE TITLE
how do you use

### ISSUE THREAD

**Issue by Cxsmo-ai** [MineEric64/BetterLiveScreen#13]
how do you use

**Comment by MineEric64** [comment]
I didn't complete these features, so you can't use BetterLiveScreen yet.
I'll tell you when I complete this project.

Thanks

**Comment by MineEric64** [comment]
now I almost completed this app, so you can use it beta. you can download it from https://github.com/MineEric64/BetterLiveScreen/releases/latest

how to use
1. In server, click the button named 'Create Room'
2. In client, type server's ip next to the button named 'Connect' and click the button named 'Connect'
3. Server and client are both connected, so you can share the screen when you click the button named 'Go Live'
4. If you want to watch the user's stream (live), click the button named 'Watch' above the user's profile and you can watch the user's stream (live).

when you have a question about this app (Better Live Screen), you can open the issue and question it.
Thanks!
