### ISSUE TITLE
특정 애플리케이션 오디오 캡쳐

### ISSUE THREAD

**Issue by Luigi38** [MineEric64/BetterLiveScreen#3]
디스코드는 특정 애플리케이션 오디오를 캡처할 때 애플리케이션 API를 후킹하여 오디오를 가져온다.
하지만 윈도우에서는 오디오를 캡처하는 공식 API가 존재하지 않아 쉽게 기능을 만들 수가 없다.

**Comment by Luigi38** [comment]
[이 문서](https://stackoverflow.com/questions/6084550/capture-audio-of-a-single-application-on-windows-7)에 따르면 Detours라는 후킹 프로그램을 통해 [IAudioRenderClient](http://msdn.microsoft.com/en-us/library/windows/desktop/dd368242%28v=vs.85%29.aspx) 라이브러리를 사용하여 오디오를 가져온다고 한다.

- [참고 문서](https://docs.microsoft.com/ko-kr/windows/win32/coreaudio/rendering-a-stream)

**Comment by Luigi38** [comment]
[OBS 오디오 캡처 라이브러리](https://github.com/bozbez/win-capture-audio) 참고.
mixer.hpp에 있는 vector<float> mix가 오디오 데이터인 듯. (추정)
mixer.hpp에 있는 source도 중요한 것 같음.

일단 라이브러리를 뜯어보자.

**Comment by MineEric64** [comment]
[EarTrumpet](https://github.com/File-New-Project/EarTrumpet) 프로젝트 참고

**Comment by MineEric64** [comment]
[AuxSense](https://github.com/SirusDoma/AuxSense) 라이브러리를 참고하여 [AudioRenderer.cs](../blob/main/Recording/Audio/AudioRender/AudioRenderer.cs)를 만들었지만, non-init issue 때문에 실제로는 사용할 수 없게 됨.

정말 아쉽다... 3일동안 코딩 왜 한거야 ㅠㅠㅠ
그래도 아직 win-capture-audio가 남아있다.
