### ISSUE TITLE
서버 형식

### ISSUE THREAD

**Issue by Luigi38** [MineEric64/BetterLiveScreen#4]
두가지 서버 형식
- 기존 서버
- P2P

**Comment by Luigi38** [comment]
기존 서버 형식으로는 서버가 주고 받는 데이터를 다 부담하고
클라이언트는 자기가 보내는 데이터와 자기가 받는 데이터만 부담하면 된다.

따라서 기존 서버가 클라이언트에 비해 많이 부담을 가질 수 밖에 없다.

클라이언트 입장에서는 부하를 많이 가지지 않으므로 장점이지만,
서버 입장에서는 클라이언트에 비해 부하를 많이 가지므로 단점이다.

**Comment by Luigi38** [comment]
P2P 형식으로는 서버가 존재하지 않으므로

클라이언트가 주고 받는 데이터를 다 부담해야 한다.
따라서 클라이언트가 데이터를 다 부담하므로

클라이언트 입장에서는 기존 서버 형식에 비해 부담을 많이 가지므로 단점이지만,
서버 입장에서는 서버가 존재하지 않으므로 서버를 안키고도 애플리케이션을 이용할 수 있고 서버에도 부담이 전혀 가지 않으므로 장점이다.

**Comment by Luigi38** [comment]
디스코드 화면 공유는 WebRTC를 통해 만들어졌다. (P2P 방식)

**Comment by Luigi38** [comment]
[WebRtc.Net](https://github.com/radioman/WebRtc.NET) 프로젝트 참고

**Comment by MineEric64** [comment]
P2P 방식으로 하기로 했음.
커넥션 방식은 방장 커넥션으로.
