### ISSUE TITLE
특정 프로그램 화면 캡처

### ISSUE THREAD

**Issue by MineEric64** [MineEric64/BetterLiveScreen#5]
1. Desktop Duplication API
물론 얘가 젤 빠르고 좋다. 하지만 일부 사용자에게는 화면이 검정인 이슈가 있다. (나도 그런 이슈가 종종 있음)
[ProjectReinforced](https://github.com/Luigi38/ProjectReinforced) 프로젝트에 사용한 API.

2. WGC (Windows.Graphics.Capture)
Windows 10부터 지원한 API이다. 아직 성능은 확인해보지 않았지만 구글링 결과
Destop Duplication API랑 WGC랑 성능 차이는 별로 없다고 한다. 한 번 써봐야 알 듯.

- [WGC 참고 글](https://jcoder1.tistory.com/344)

**Comment by MineEric64** [comment]
8969da0 커밋으로 Desktop Duplication, Windows.Graphics.Capture 다 구현했다.

CPU (i5-6400)
GPU (GTX 1050Ti)
기준으로

2560x1440 (QHD) 해상도 Desktop 평균 프레임
DD : 45fps
WGC : 55fps~65fps

2560x1440 (QHD) 해상도 인게임 평균 프레임
DD : 7fps
WGC : 7fps

1280x720 (HD) 해상도이 인게임 평균 프레임
DD : 30fps
WGC : 30fps

테스트 결과 DD와 WGC 둘 다 성능이 크게 차이는 없었음. 애초에 WGC 구현할 때 DD 방식이랑 닮기도 했고.

그래서 둘 다 뛰어넘을 수 있는 무언가의 혁신이 필요했음.

8969da0 커밋으로 Nvenc 인코딩이 가능해짐.
아직 인게임에서 테스트 해보지 않았지만 Desktop에서 Resolution이 0ms에 근접한 수준인거 보면 진짜 GPU가 빠르긴 함. (Color Issue, Bitrate too low 문제도 있어서 정확한 테스트 필요)

오늘 영재원 끝나고 집 가서 Nvenc 관련 오류 고치고 테스트해볼 듯.

이 모든게 3일만에 구현됨.
물론 평균 10시간 코딩 & 디버깅해서 가능한거임.

**Comment by Luigi38** [comment]
영재원 컴퓨터로 Desktop Duplication (DD), Windows.Graphics.Capture (WGC) 테스트 결과

[기준 - 1920x1080 (FHD) Desktop
CPU - i7-11700,
GPU - Intel UHD Graphics 750]
둘 다 CPU 점유율은 5~10% 수준이였다. 이 정도면 굳

평균 프레임 (DD) : 45fps
평균 프레임 (WGC) : 60fps

이다. 영재원 컴퓨터는 롤이 돌아가긴 하지만
지금은 대회 시간이므로 롤을 돌릴 수 없다.

확실히 낮은 사양일 수록 WGC 성능이 Destop Duplication보다 좋긴 한 것 같다.

**Comment by Luigi38** [comment]
만약 화면을 전송할 때 Jpeg로 인코딩할거면 libjpeg-turbo를 사용하자!

**Comment by MineEric64** [comment]
[기준 - 2560x1440 (QHD) 인게임,
CPU - i5-6400,
GPU - GTX 1050Ti,
Nvenc 인코딩 활성화]

CPU는 거의 점유율을 가지지 않았다.
GPU도 20% 정도 점유율 가지는거 보면 매우 효율적이다.

평균 프레임 : 72프레임
QHD에 인게임이 72프레임이면 진짜진짜 효율적인거다!!

매우 성공적이다.

디스코드가 이런 기술을 공개하고 있지 않지만,
디스코드가 DXGI 데스크탑 복사 (Desktop Duplication)랑 Nvenc (NvEncoder, NvPipe)를 사용하는 것 같다.
