### ISSUE TITLE
build error while implementing Windows.Graphics.Capture

### ISSUE THREAD

**Issue by Luigi38** [MineEric64/BetterLiveScreen#6]
집에서는 하루동안 개**해봤는데 삽질이였지만,
넥스탑 컴퓨터로 하니깐 바로 해결.

SDK 설치해봤는데 안됨.
근데 WindowsAppSDK.Foundation 제거했는데 해결.

혹시 모르니 참고
![제목 없음](https://user-images.githubusercontent.com/71323379/197376741-58a621fc-29cd-44f0-93cb-930b912abb9e.png)

**Comment by MineEric64** [comment]
sugo because of 13983dc8d5c5dee112308ab780b92a23302903b1
