### ISSUE TITLE
Nvenc 인코딩 관련 문제

### ISSUE THREAD

**Issue by MineEric64** [MineEric64/BetterLiveScreen#7]
8969da0 커밋 기준 문제 정리
1. Color Issue
색상이 이상함. 주황색이 하늘색으로 보이는 문제가 있음.
BGRA로 저장해야 하는걸 RGBA로 저장해서 나타나는 문제인걸로 추정.

2. Bitrate too low
비트레이트를 높였는데도 불구하고 비트레이트가 너무 낮아서 화면이 뭉개짐. 이게 QHD가 맞나 의심될 정도로.
이건 이유를 잘 모르겠어서 연구 필요.

문제는 아니고 개선 사항
1. Nvenc 인코딩 지원 안하면?
`Encoder.Create()` 하고 `IsValid`가 `false`이라면 `Rescreen.NvencEncoding`을 비활성화하게 만들 수 있다.

2. WGC에도 적용
8969da0 커밋 기준으로 WGC에는 적용 안됨.

**Comment by Luigi38** [comment]
3. WGC 지원 안하면?
`Recording/Video/WGC/WGCHelper.cs`에 `IsInitialized` 변수 추가한 다음 `Initialize()` 함수에 `IsInitialized` 변수를 초기화한다.
그리고 만약 `IsInitialized`가 `false`라면 WGC 대신 Desktop Duplication을 이용하는 방식이다.

**Comment by Luigi38** [comment]
[Bitrate too low]
아이디어가 떠오른건 아니지만
[라이브 스트리밍 권장 비트레이트 문서](https://support.google.com/youtube/answer/2853702?hl=en#zippy=)를 참고하자.

**Comment by Luigi38** [comment]
[Bitrate too low]
기본 비트레이트 값 `float bitrateMbps_ = 32;`

**Comment by Luigi38** [comment]
[Color Issue & Bitrate too low]
```c++
struct NvencDesc
{
    ComPtr<ID3D11Device> d3d11Device; 
    uint32_t width = 1920; 
    uint32_t height = 1080;
    DXGI_FORMAT format = DXGI_FORMAT_R8G8B8A8_UNORM;
    uint32_t frameRate = 60;
    uint32_t bitRate = 2'000'000;
    uint32_t maxFrameSize = 2'000'000 / 60;
};
```

Nvenc.cpp in NvEncoder
Have to fix?

**Comment by Luigi38** [comment]
[Color Issue]
NvEncoder/Nvenc.cpp에서 주범이 많은 것 같은데?

**Comment by Luigi38** [comment]
[Color Issue]
https://www.ffmpeg.org/doxygen/3.3/group__ENCODER__STRUCTURE.html 에서 NV_ENC_BUFFER_FORMAT 찾다보면
나옴!!! 이거 꽤 도움될지도?

**Comment by Luigi38** [comment]
[Color Issue]
NvPipe는 그냥 RGBA32 하고 안되면 UINT32 하는것도 나쁘지 않을지도?

**Comment by Luigi38** [comment]
NVENC 개선 사항
CBR -> VBR 나쁘지 않을지도? 그대신 low latency 모드는 지원되지 않을 수도 있음.
테스트 필요.

https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-video-encoder-api-prog-guide 참고 (vbr 찾기)

**Comment by MineEric64** [comment]
> NVENC 개선 사항 CBR -> VBR 나쁘지 않을지도? 그대신 low latency 모드는 지원되지 않을 수도 있음. 테스트 필요.
> 
> https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-video-encoder-api-prog-guide 참고 (vbr 찾기)

이 기능은 그냥 아직 안해봤음.
좀 느리거나 Bitrate 관련 문제가 나올 경우 이거 써볼 듯.

지금까지는 해결된 문제
